### ISSUE TITLE
angular acceleration in task 2.14

### ISSUE THREAD

**Issue by Avens8** [uteshev/mipt3.anmech#6]
Формула (20). Ускорение получается путем двойного дифференцирования угла по времени в точке t = pi / w. То есть получится - sin (wt). Почему не ноль?

**Comment by uteshev** [comment]
Получится &ndash;&thinsp;w<sup>2</sup> sin(wt).
Согласен, скорее всего, зарапортовался.
С утра проверю и исправлю, спасибо!

**Comment by uteshev** [comment]
@Avens8, спасибо ещё раз!
